# Setup
title:            move-iit-hpe
tagline:          'Event-camera HPE'
description:      'An event-camera Human Pose Estimation dataset and competition'
url:              https://event-driven-robotics.github.io
baseurl:          ''
paginate:         5

# About and contact
author:
  name:           'Event-driven Perception for Robotics'
  url:            https://www.edpr.iit.it

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          0.1
